package isilimageprocessing;

import CImage.*;
import CImage.Exceptions.*;
import CImage.Observers.*;
import CImage.Observers.Events.*;
import ImageProcessing.Complexe.MatriceComplexe;
import ImageProcessing.Contours.ContoursLineaire;
import ImageProcessing.Contours.ContoursNonLineaire;
import ImageProcessing.Fourier.Fourier;
import ImageProcessing.Histogramme.Histogramme;
import ImageProcessing.Lineaire.FiltrageLineaireGlobal;
import ImageProcessing.Lineaire.FiltrageLineaireLocal;
import ImageProcessing.NonLineaire.MorphoComplexe;
import ImageProcessing.NonLineaire.MorphoElementaire;
import ImageProcessing.Seuillage.Seuillage;
import isilimageprocessing.Dialogues.*;
import java.awt.*;
import java.io.*;
import java.util.Objects;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class IsilImageProcessing extends javax.swing.JFrame implements ClicListener,SelectLigneListener,SelectRectListener,SelectRectFillListener,SelectCercleListener,SelectCercleFillListener 
{
    private CImageRGB imageRGB;
    private CImageNG  imageNG;
    private final JLabelBeanCImage observer;
    private Color couleurPinceauRGB;
    private int   couleurPinceauNG;
    
    /** Creates new form TestCImage2 */
    public IsilImageProcessing() 
    {
        initComponents();
        
        imageRGB = null;
        imageNG  = null;
        
        observer = new JLabelBeanCImage();
        observer.addClicListener(this);
        observer.addSelectLigneListener(this);
        observer.addSelectRectListener(this);
        observer.addSelectRectFillListener(this);
        observer.addSelectCercleListener(this);
        observer.addSelectCercleFillListener(this);
        observer.setMode(JLabelBeanCImage.INACTIF);
        jScrollPane.setViewportView(observer);
        
        jMenuDessiner.setEnabled(false);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
        jMenuContours.setEnabled(false);
        jMenuSeuillage.setEnabled(false);
        jMenuFiltrageLineaire.setEnabled(false);
        jMenuTraitementNonLineaire.setEnabled(false);
        
        couleurPinceauRGB = Color.BLACK;
        couleurPinceauNG = 0;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    private void initComponents() {

        buttonGroupDessiner = new javax.swing.ButtonGroup();
        jScrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuImage = new javax.swing.JMenu();
        jMenuNouvelle = new javax.swing.JMenu();
        jMenuItemNouvelleRGB = new javax.swing.JMenuItem();
        jMenuItemNouvelleNG = new javax.swing.JMenuItem();
        jMenuOuvrir = new javax.swing.JMenu();
        jMenuItemOuvrirRGB = new javax.swing.JMenuItem();
        jMenuItemOuvrirNG = new javax.swing.JMenuItem();
        jMenuItemEnregistrerSous = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuQuitter = new javax.swing.JMenuItem();
        jMenuDessiner = new javax.swing.JMenu();
        jMenuItemCouleurPinceau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBoxMenuItemDessinerPixel = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerLigne = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectangle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectanglePlein = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCercle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCerclePlein = new javax.swing.JCheckBoxMenuItem();
        jMenuFourier = new javax.swing.JMenu();
        jMenuFourierAfficher = new javax.swing.JMenu();
        jMenuItemFourierAfficherModule = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPhase = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieReelle = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieImaginaire = new javax.swing.JMenuItem();
        jMenuHistogramme = new javax.swing.JMenu();
        jMenuHistogrammeAfficher = new javax.swing.JMenuItem();
        jMenuHistogrammeParametres = new javax.swing.JMenuItem();
        jMenuHistogrammeRehaussement = new javax.swing.JMenu();
        jMenuItemHistogrammeLineaire = new javax.swing.JMenuItem();
        jMenuItemHistogrammeLineaireSaturation = new javax.swing.JMenuItem();
        jMenuItemHistogrammeGamma = new javax.swing.JMenuItem();
        jMenuItemHistogrammeEgalisation = new javax.swing.JMenuItem();
        jMenuItemHistogrammeNegatif = new javax.swing.JMenuItem();
        jMenuContours = new javax.swing.JMenu();
        jMenuContoursLineaire = new javax.swing.JMenu();
        jMenuItemContoursGradientPrewitt = new javax.swing.JMenuItem();
        jMenuItemContoursGradientSobel = new javax.swing.JMenuItem();
        jMenuItemContoursLaplacien4 = new javax.swing.JMenuItem();
        jMenuItemContoursLaplacien8 = new javax.swing.JMenuItem();
        jMenuContoursNonLineaire = new javax.swing.JMenu();
        jMenuItemContoursGradientErosion = new javax.swing.JMenuItem();
        jMenuItemContoursGradientDilatation = new javax.swing.JMenuItem();
        jMenuItemContoursGradientBeucher = new javax.swing.JMenuItem();
        jMenuItemContoursLaplacienNonLineaire = new javax.swing.JMenuItem();
        jMenuSeuillage = new javax.swing.JMenu();
        jMenuItemSeuillageSimple = new javax.swing.JMenuItem();
        jMenuItemSeuillageDouble = new javax.swing.JMenuItem();
        jMenuItemSeuillageAutomatique = new javax.swing.JMenuItem();
        jMenuFiltrageLineaire = new javax.swing.JMenu();
        jMenuFiltrageLineaireGlobal = new javax.swing.JMenu();
        jMenuItemFiltrePasseBasIdeal = new javax.swing.JMenuItem();
        jMenuItemFiltrePasseHautIdeal = new javax.swing.JMenuItem();
        jMenuItemFiltrePasseBasButterworth = new javax.swing.JMenuItem();
        jMenuItemFiltrePasseHautButterworth = new javax.swing.JMenuItem();
        jMenuFiltrageLineaireLocal = new javax.swing.JMenu();
        jMenuItemFiltreMasqueConvolution = new javax.swing.JMenuItem();
        jMenuItemFiltreMoyenneur = new javax.swing.JMenuItem();
        jMenuTraitementNonLineaire = new javax.swing.JMenu();
        jMenuMorphoElementaire = new javax.swing.JMenu();
        jMenuItemMorphoErosion = new javax.swing.JMenuItem();
        jMenuItemMorphoDilatation = new javax.swing.JMenuItem();
        jMenuItemMorphoOuverture = new javax.swing.JMenuItem();
        jMenuItemMorphoFermeture = new javax.swing.JMenuItem();
        jMenuMorphoComplexe = new javax.swing.JMenu();
        jMenuItemMorphoDilatationGeodesique = new javax.swing.JMenuItem();
        jMenuItemMorphoReconstructionGeodesique = new javax.swing.JMenuItem();
        jMenuItemMorphoFiltreMedian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Isil Image Processing");

        jMenuImage.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/Net 13_p1.jpg")))); // NOI18N
        jMenuImage.setText("Image");

        jMenuNouvelle.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/File 65_p3.jpg")))); // NOI18N
        jMenuNouvelle.setText("Nouvelle");

        jMenuItemNouvelleRGB.setText("Image RGB");
        jMenuItemNouvelleRGB.addActionListener(this::jMenuItemNouvelleRGBActionPerformed);
        jMenuNouvelle.add(jMenuItemNouvelleRGB);

        jMenuItemNouvelleNG.setText("Image NG");
        jMenuItemNouvelleNG.addActionListener(this::jMenuItemNouvelleNGActionPerformed);
        jMenuNouvelle.add(jMenuItemNouvelleNG);

        jMenuImage.add(jMenuNouvelle);

        jMenuOuvrir.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/Folder 036_p3.jpg")))); // NOI18N
        jMenuOuvrir.setText("Ouvrir");

        jMenuItemOuvrirRGB.setText("Image RGB");
        jMenuItemOuvrirRGB.addActionListener(this::jMenuItemOuvrirRGBActionPerformed);
        jMenuOuvrir.add(jMenuItemOuvrirRGB);

        jMenuItemOuvrirNG.setText("Image NG");
        jMenuItemOuvrirNG.addActionListener(this::jMenuItemOuvrirNGActionPerformed);
        jMenuOuvrir.add(jMenuItemOuvrirNG);

        jMenuImage.add(jMenuOuvrir);

        jMenuItemEnregistrerSous.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/DD 27_p3.jpg")))); // NOI18N
        jMenuItemEnregistrerSous.setText("Enregistrer sous...");
        jMenuItemEnregistrerSous.addActionListener(this::jMenuItemEnregistrerSousActionPerformed);
        jMenuImage.add(jMenuItemEnregistrerSous);
        jMenuImage.add(jSeparator1);

        jMenuQuitter.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/CP 59_p3.jpg")))); // NOI18N
        jMenuQuitter.setText("Quitter");
        jMenuQuitter.addActionListener(this::jMenuQuitterActionPerformed);
        jMenuImage.add(jMenuQuitter);

        jMenuBar1.add(jMenuImage);

        jMenuDessiner.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/Display 28_p1.jpg")))); // NOI18N
        jMenuDessiner.setText("Dessiner");

        jMenuItemCouleurPinceau.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/Display 14_p3.jpg")))); // NOI18N
        jMenuItemCouleurPinceau.setText("Couleur");
        jMenuItemCouleurPinceau.addActionListener(this::jMenuItemCouleurPinceauActionPerformed);
        jMenuDessiner.add(jMenuItemCouleurPinceau);
        jMenuDessiner.add(jSeparator2);

        jCheckBoxMenuItemDessinerPixel.setText("Pixel");
        jCheckBoxMenuItemDessinerPixel.addActionListener(this::jCheckBoxMenuItemDessinerPixelActionPerformed);
        jMenuDessiner.add(jCheckBoxMenuItemDessinerPixel);

        jCheckBoxMenuItemDessinerLigne.setText("Ligne");
        jCheckBoxMenuItemDessinerLigne.addActionListener(this::jCheckBoxMenuItemDessinerLigneActionPerformed);
        jMenuDessiner.add(jCheckBoxMenuItemDessinerLigne);

        jCheckBoxMenuItemDessinerRectangle.setText("Rectangle");
        jCheckBoxMenuItemDessinerRectangle.addActionListener(this::jCheckBoxMenuItemDessinerRectangleActionPerformed);
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectangle);

        jCheckBoxMenuItemDessinerRectanglePlein.setText("Rectangle plein");
        jCheckBoxMenuItemDessinerRectanglePlein.addActionListener(this::jCheckBoxMenuItemDessinerRectanglePleinActionPerformed);
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectanglePlein);

        jCheckBoxMenuItemDessinerCercle.setText("Cercle");
        jCheckBoxMenuItemDessinerCercle.addActionListener(this::jCheckBoxMenuItemDessinerCercleActionPerformed);
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCercle);

        jCheckBoxMenuItemDessinerCerclePlein.setText("Cercle plein");
        jCheckBoxMenuItemDessinerCerclePlein.addActionListener(this::jCheckBoxMenuItemDessinerCerclePleinActionPerformed);
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCerclePlein);

        jMenuBar1.add(jMenuDessiner);

        jMenuFourier.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/CP 51_p1.jpg")))); // NOI18N
        jMenuFourier.setText("Fourier");

        jMenuFourierAfficher.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/CP 51_p3.jpg")))); // NOI18N
        jMenuFourierAfficher.setText("Afficher");

        jMenuItemFourierAfficherModule.setText("Module");
        jMenuItemFourierAfficherModule.addActionListener(this::jMenuItemFourierAfficherModuleActionPerformed);
        jMenuFourierAfficher.add(jMenuItemFourierAfficherModule);

        jMenuItemFourierAfficherPhase.setText("Phase");
        jMenuItemFourierAfficherPhase.addActionListener(this::jMenuItemFourierAfficherPhaseActionPerformed);
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPhase);

        jMenuItemFourierAfficherPartieReelle.setText("Partie Réelle");
        jMenuItemFourierAfficherPartieReelle.addActionListener(this::jMenuItemFourierAfficherPartieReelleActionPerformed);
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieReelle);

        jMenuItemFourierAfficherPartieImaginaire.setText("Partie Imaginaire");
        jMenuItemFourierAfficherPartieImaginaire.addActionListener(this::jMenuItemFourierAfficherPartieImaginaireActionPerformed);
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieImaginaire);

        jMenuFourier.add(jMenuFourierAfficher);

        jMenuBar1.add(jMenuFourier);

        jMenuHistogramme.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/report_48_hot.jpg")))); // NOI18N
        jMenuHistogramme.setText("Histogramme");

        jMenuHistogrammeAfficher.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Icones/report_32_hot.jpg")))); // NOI18N
        jMenuHistogrammeAfficher.setText("Afficher");
        jMenuHistogrammeAfficher.addActionListener(this::jMenuHistogrammeAfficherActionPerformed);
        jMenuHistogramme.add(jMenuHistogrammeAfficher);

        jMenuHistogrammeParametres.setText("Afficher les parametres de l'image");
        jMenuHistogrammeParametres.addActionListener(this::jMenuHistogrammeParametresActionPerformed);
        jMenuHistogramme.add(jMenuHistogrammeParametres);

        jMenuHistogrammeRehaussement.setText("Rehaussement");
        ajouteTraceMenu(jMenuHistogrammeRehaussement, "Histogramme > Rehaussement");

        jMenuItemHistogrammeLineaire.setText("Lineaire");
        jMenuItemHistogrammeLineaire.addActionListener(this::jMenuItemHistogrammeLineaireActionPerformed);
        jMenuHistogrammeRehaussement.add(jMenuItemHistogrammeLineaire);

        jMenuItemHistogrammeLineaireSaturation.setText("Lineaire avec saturation");
        jMenuItemHistogrammeLineaireSaturation.addActionListener(this::jMenuItemHistogrammeLineaireSaturationActionPerformed);
        jMenuHistogrammeRehaussement.add(jMenuItemHistogrammeLineaireSaturation);

        jMenuItemHistogrammeGamma.setText("Gamma");
        jMenuItemHistogrammeGamma.addActionListener(this::jMenuItemHistogrammeGammaActionPerformed);
        jMenuHistogrammeRehaussement.add(jMenuItemHistogrammeGamma);

        jMenuItemHistogrammeEgalisation.setText("Egalisation");
        jMenuItemHistogrammeEgalisation.addActionListener(this::jMenuItemHistogrammeEgalisationActionPerformed);
        jMenuHistogrammeRehaussement.add(jMenuItemHistogrammeEgalisation);

        jMenuItemHistogrammeNegatif.setText("Negatif");
        jMenuItemHistogrammeNegatif.addActionListener(this::jMenuItemHistogrammeNegatifActionPerformed);
        jMenuHistogrammeRehaussement.add(jMenuItemHistogrammeNegatif);

        jMenuHistogramme.add(jMenuHistogrammeRehaussement);

        jMenuBar1.add(jMenuHistogramme);

        jMenuContours.setText("Contours");
        ajouteTraceMenu(jMenuContours, "Contours");

        jMenuContoursLineaire.setText("Lineaire");
        ajouteTraceMenu(jMenuContoursLineaire, "Contours > Lineaire");

        jMenuItemContoursGradientPrewitt.setText("Gradient Prewitt");
        jMenuItemContoursGradientPrewitt.addActionListener(this::jMenuItemContoursGradientPrewittActionPerformed);
        jMenuContoursLineaire.add(jMenuItemContoursGradientPrewitt);

        jMenuItemContoursGradientSobel.setText("Gradient Sobel");
        jMenuItemContoursGradientSobel.addActionListener(this::jMenuItemContoursGradientSobelActionPerformed);
        jMenuContoursLineaire.add(jMenuItemContoursGradientSobel);

        jMenuItemContoursLaplacien4.setText("Laplacien 4");
        jMenuItemContoursLaplacien4.addActionListener(this::jMenuItemContoursLaplacien4ActionPerformed);
        jMenuContoursLineaire.add(jMenuItemContoursLaplacien4);

        jMenuItemContoursLaplacien8.setText("Laplacien 8");
        jMenuItemContoursLaplacien8.addActionListener(this::jMenuItemContoursLaplacien8ActionPerformed);
        jMenuContoursLineaire.add(jMenuItemContoursLaplacien8);

        jMenuContours.add(jMenuContoursLineaire);

        jMenuContoursNonLineaire.setText("Non-lineaire");
        ajouteTraceMenu(jMenuContoursNonLineaire, "Contours > Non-lineaire");

        jMenuItemContoursGradientErosion.setText("Gradient erosion");
        jMenuItemContoursGradientErosion.addActionListener(this::jMenuItemContoursGradientErosionActionPerformed);
        jMenuContoursNonLineaire.add(jMenuItemContoursGradientErosion);

        jMenuItemContoursGradientDilatation.setText("Gradient dilatation");
        jMenuItemContoursGradientDilatation.addActionListener(this::jMenuItemContoursGradientDilatationActionPerformed);
        jMenuContoursNonLineaire.add(jMenuItemContoursGradientDilatation);

        jMenuItemContoursGradientBeucher.setText("Gradient Beucher");
        jMenuItemContoursGradientBeucher.addActionListener(this::jMenuItemContoursGradientBeucherActionPerformed);
        jMenuContoursNonLineaire.add(jMenuItemContoursGradientBeucher);

        jMenuItemContoursLaplacienNonLineaire.setText("Laplacien non-lineaire");
        jMenuItemContoursLaplacienNonLineaire.addActionListener(this::jMenuItemContoursLaplacienNonLineaireActionPerformed);
        jMenuContoursNonLineaire.add(jMenuItemContoursLaplacienNonLineaire);

        jMenuContours.add(jMenuContoursNonLineaire);

        jMenuBar1.add(jMenuContours);

        jMenuSeuillage.setText("Seuillage");
        ajouteTraceMenu(jMenuSeuillage, "Seuillage");

        jMenuItemSeuillageSimple.setText("Seuillage simple");
        jMenuItemSeuillageSimple.addActionListener(this::jMenuItemSeuillageSimpleActionPerformed);
        jMenuSeuillage.add(jMenuItemSeuillageSimple);

        jMenuItemSeuillageDouble.setText("Seuillage double");
        jMenuItemSeuillageDouble.addActionListener(this::jMenuItemSeuillageDoubleActionPerformed);
        jMenuSeuillage.add(jMenuItemSeuillageDouble);

        jMenuItemSeuillageAutomatique.setText("Seuillage automatique");
        jMenuItemSeuillageAutomatique.addActionListener(this::jMenuItemSeuillageAutomatiqueActionPerformed);
        jMenuSeuillage.add(jMenuItemSeuillageAutomatique);

        jMenuBar1.add(jMenuSeuillage);

        jMenuFiltrageLineaire.setText("Filtrage linéaire");
        ajouteTraceMenu(jMenuFiltrageLineaire, "Filtrage linéaire");

        jMenuFiltrageLineaireGlobal.setText("Global");
        ajouteTraceMenu(jMenuFiltrageLineaireGlobal, "Filtrage linéaire > Global");

        jMenuItemFiltrePasseBasIdeal.setText("Passe-bas idéal");
        jMenuItemFiltrePasseBasIdeal.addActionListener(this::jMenuItemFiltrePasseBasIdealActionPerformed);
        jMenuFiltrageLineaireGlobal.add(jMenuItemFiltrePasseBasIdeal);

        jMenuItemFiltrePasseHautIdeal.setText("Passe-haut idéal");
        jMenuItemFiltrePasseHautIdeal.addActionListener(this::jMenuItemFiltrePasseHautIdealActionPerformed);
        jMenuFiltrageLineaireGlobal.add(jMenuItemFiltrePasseHautIdeal);

        jMenuItemFiltrePasseBasButterworth.setText("Passe-bas Butterworth");
        jMenuItemFiltrePasseBasButterworth.addActionListener(this::jMenuItemFiltrePasseBasButterworthActionPerformed);
        jMenuFiltrageLineaireGlobal.add(jMenuItemFiltrePasseBasButterworth);

        jMenuItemFiltrePasseHautButterworth.setText("Passe-haut Butterworth");
        jMenuItemFiltrePasseHautButterworth.addActionListener(this::jMenuItemFiltrePasseHautButterworthActionPerformed);
        jMenuFiltrageLineaireGlobal.add(jMenuItemFiltrePasseHautButterworth);

        jMenuFiltrageLineaire.add(jMenuFiltrageLineaireGlobal);

        jMenuFiltrageLineaireLocal.setText("Local");
        ajouteTraceMenu(jMenuFiltrageLineaireLocal, "Filtrage linéaire > Local");

        jMenuItemFiltreMasqueConvolution.setText("Masque de convolution");
        jMenuItemFiltreMasqueConvolution.addActionListener(this::jMenuItemFiltreMasqueConvolutionActionPerformed);
        jMenuFiltrageLineaireLocal.add(jMenuItemFiltreMasqueConvolution);

        jMenuItemFiltreMoyenneur.setText("Moyenneur");
        jMenuItemFiltreMoyenneur.addActionListener(this::jMenuItemFiltreMoyenneurActionPerformed);
        jMenuFiltrageLineaireLocal.add(jMenuItemFiltreMoyenneur);

        jMenuFiltrageLineaire.add(jMenuFiltrageLineaireLocal);

        jMenuBar1.add(jMenuFiltrageLineaire);

        jMenuTraitementNonLineaire.setText("Traitement non-linéaire");
        ajouteTraceMenu(jMenuTraitementNonLineaire, "Traitement non-linéaire");

        jMenuMorphoElementaire.setText("Elémentaire");
        ajouteTraceMenu(jMenuMorphoElementaire, "Traitement non-linéaire > Elémentaire");

        jMenuItemMorphoErosion.setText("Erosion");
        jMenuItemMorphoErosion.addActionListener(this::jMenuItemMorphoErosionActionPerformed);
        jMenuMorphoElementaire.add(jMenuItemMorphoErosion);

        jMenuItemMorphoDilatation.setText("Dilatation");
        jMenuItemMorphoDilatation.addActionListener(this::jMenuItemMorphoDilatationActionPerformed);
        jMenuMorphoElementaire.add(jMenuItemMorphoDilatation);

        jMenuItemMorphoOuverture.setText("Ouverture");
        jMenuItemMorphoOuverture.addActionListener(this::jMenuItemMorphoOuvertureActionPerformed);
        jMenuMorphoElementaire.add(jMenuItemMorphoOuverture);

        jMenuItemMorphoFermeture.setText("Fermeture");
        jMenuItemMorphoFermeture.addActionListener(this::jMenuItemMorphoFermetureActionPerformed);
        jMenuMorphoElementaire.add(jMenuItemMorphoFermeture);

        jMenuTraitementNonLineaire.add(jMenuMorphoElementaire);

        jMenuMorphoComplexe.setText("Complexe");
        ajouteTraceMenu(jMenuMorphoComplexe, "Traitement non-linéaire > Complexe");

        jMenuItemMorphoDilatationGeodesique.setText("Dilatation géodésique");
        jMenuItemMorphoDilatationGeodesique.addActionListener(this::jMenuItemMorphoDilatationGeodesiqueActionPerformed);
        jMenuMorphoComplexe.add(jMenuItemMorphoDilatationGeodesique);

        jMenuItemMorphoReconstructionGeodesique.setText("Reconstruction géodésique");
        jMenuItemMorphoReconstructionGeodesique.addActionListener(this::jMenuItemMorphoReconstructionGeodesiqueActionPerformed);
        jMenuMorphoComplexe.add(jMenuItemMorphoReconstructionGeodesique);

        jMenuItemMorphoFiltreMedian.setText("Filtre médian");
        jMenuItemMorphoFiltreMedian.addActionListener(this::jMenuItemMorphoFiltreMedianActionPerformed);
        jMenuMorphoComplexe.add(jMenuItemMorphoFiltreMedian);

        jMenuTraitementNonLineaire.add(jMenuMorphoComplexe);

        jMenuBar1.add(jMenuTraitementNonLineaire);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(500, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHistogrammeAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistogrammeAfficherActionPerformed
        int[] histo;
        try 
        {
            int[][] f_int = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        
        // Cr�ation du dataset
        XYSeries serie = new XYSeries("Histo");
        for(int i=0 ; i<256 ; i++) serie.add(i,histo[i]);
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(serie);
        
        // Creation du chart
        JFreeChart chart = ChartFactory.createHistogram("Histogramme","Niveaux de gris","Nombre de pixels",dataset,PlotOrientation.VERTICAL,false,false,false);

        XYPlot plot = chart.getXYPlot();
        ValueAxis axeX = plot.getDomainAxis();
        axeX.setRange(0,255);
        plot.setDomainAxis(axeX);
        
        // creation d'une frame
        ChartFrame frame = new ChartFrame("Histogramme de l'image",chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuHistogrammeAfficherActionPerformed

    private void jMenuHistogrammeParametresActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Histogramme > Afficher les parametres de l'image");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        int minimum = Histogramme.minimum(matrice);
        int maximum = Histogramme.maximum(matrice);
        int luminance = Histogramme.luminance(matrice);
        double contraste1 = Histogramme.contraste1(matrice);
        double contraste2 = Histogramme.contraste2(matrice);

        JOptionPane.showMessageDialog(this,
                "Minimum : " + minimum + "\n"
                + "Maximum : " + maximum + "\n"
                + "Luminance : " + luminance + "\n"
                + "Contraste 1 : " + contraste1 + "\n"
                + "Contraste 2 : " + contraste2,
                "Parametres de l'image",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void jMenuItemHistogrammeLineaireActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Histogramme > Rehaussement > Lineaire");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        int minimum = Histogramme.minimum(matrice);
        int maximum = Histogramme.maximum(matrice);
        int[] courbeTonale = Histogramme.creeCourbeTonaleLineaireSaturation(minimum, maximum);
        appelleRehaussementAvecHistogrammes(matrice, courbeTonale, "lineaire");
    }

    private void jMenuItemHistogrammeLineaireSaturationActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Histogramme > Rehaussement > Lineaire avec saturation");
        Integer smin = demandeEntier("smin", 0);
        if (smin == null) return;
        Integer smax = demandeEntier("smax", 0);
        if (smax == null) return;

        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        int[] courbeTonale = Histogramme.creeCourbeTonaleLineaireSaturation(smin, smax);
        appelleRehaussementAvecHistogrammes(matrice, courbeTonale, "lineaire avec saturation");
    }

    private void jMenuItemHistogrammeGammaActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Histogramme > Rehaussement > Gamma");
        Double gamma = demandeDouble("Gamma", 0.1);
        if (gamma == null) return;

        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        int[] courbeTonale = Histogramme.creeCourbeTonaleGamma(gamma);
        appelleRehaussementAvecHistogrammes(matrice, courbeTonale, "gamma");
    }

    private void jMenuItemHistogrammeEgalisationActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Histogramme > Rehaussement > Egalisation");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        int[] courbeTonale = Histogramme.creeCourbeTonaleEgalisation(matrice);
        appelleRehaussementAvecHistogrammes(matrice, courbeTonale, "egalisation");
    }

    private void jMenuItemHistogrammeNegatifActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Histogramme > Rehaussement > Negatif");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        int[] courbeTonale = Histogramme.creeCourbeTonaleNegatif();
        appelleRehaussementAvecHistogrammes(matrice, courbeTonale, "negatif");
    }

    private void appelleRehaussementAvecHistogrammes(int[][] matrice, int[] courbeTonale, String libelle) {
        int[] histogrammeAvant = Histogramme.Histogramme256(matrice);
        afficheHistogramme(histogrammeAvant, "Histogramme avant rehaussement " + libelle);

        int[][] imageRehaussee = Histogramme.rehaussement(matrice, courbeTonale);
        if (imageRehaussee == null) {
            System.out.println("Le rehaussement " + libelle + " n'a pas retourne d'image.");
            return;
        }

        int[] histogrammeApres = Histogramme.Histogramme256(imageRehaussee);
        afficheHistogramme(histogrammeApres, "Histogramme apres rehaussement " + libelle);
    }

    private void afficheHistogramme(int[] histo, String titre) {
        XYSeries serie = new XYSeries(titre);
        for (int i = 0; i < 256; i++) serie.add(i, histo[i]);
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(serie);

        JFreeChart chart = ChartFactory.createHistogram(titre, "Niveaux de gris", "Nombre de pixels", dataset, PlotOrientation.VERTICAL, false, false, false);

        XYPlot plot = chart.getXYPlot();
        ValueAxis axeX = plot.getDomainAxis();
        axeX.setRange(0, 255);
        plot.setDomainAxis(axeX);

        ChartFrame frame = new ChartFrame(titre, chart);
        frame.pack();
        frame.setVisible(true);
    }

    private void jMenuItemContoursGradientPrewittActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Lineaire > Gradient Prewitt");
        Integer direction = demandeDirectionContour();
        if (direction == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursLineaire.gradientPrewitt(matrice, direction), "gradient Prewitt");
    }

    private void jMenuItemContoursGradientSobelActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Lineaire > Gradient Sobel");
        Integer direction = demandeDirectionContour();
        if (direction == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursLineaire.gradientSobel(matrice, direction), "gradient Sobel");
    }

    private void jMenuItemContoursLaplacien4ActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Lineaire > Laplacien 4");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursLineaire.laplacien4(matrice), "laplacien 4");
    }

    private void jMenuItemContoursLaplacien8ActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Lineaire > Laplacien 8");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursLineaire.laplacien8(matrice), "laplacien 8");
    }

    private void jMenuItemContoursGradientErosionActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Non-lineaire > Gradient erosion");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursNonLineaire.gradientErosion(matrice), "gradient erosion");
    }

    private void jMenuItemContoursGradientDilatationActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Non-lineaire > Gradient dilatation");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursNonLineaire.gradientDilatation(matrice), "gradient dilatation");
    }

    private void jMenuItemContoursGradientBeucherActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Non-lineaire > Gradient Beucher");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursNonLineaire.gradientBeucher(matrice), "gradient Beucher");
    }

    private void jMenuItemContoursLaplacienNonLineaireActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Contours > Non-lineaire > Laplacien non-lineaire");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(ContoursNonLineaire.laplacienNonLineaire(matrice), "laplacien non-lineaire");
    }

    private void jMenuItemSeuillageSimpleActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Seuillage > Seuillage simple");
        Integer seuil = demandeEntier("Seuil", 0);
        if (seuil == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(Seuillage.seuillageSimple(matrice, seuil), "seuillage simple");
    }

    private void jMenuItemSeuillageDoubleActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Seuillage > Seuillage double");
        Integer seuil1 = demandeEntier("Seuil 1", 0);
        if (seuil1 == null) return;
        Integer seuil2 = demandeEntier("Seuil 2", 0);
        if (seuil2 == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(Seuillage.seuillageDouble(matrice, seuil1, seuil2), "seuillage double");
    }

    private void jMenuItemSeuillageAutomatiqueActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Seuillage > Seuillage automatique");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueResultatStub(Seuillage.seuillageAutomatique(matrice), "seuillage automatique");
    }

    private Integer demandeDirectionContour() {
        Object[] choix = {"Horizontale", "Verticale"};
        int reponse = JOptionPane.showOptionDialog(this, "Direction du gradient :", "Direction", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, choix, choix[0]);
        if (reponse == JOptionPane.CLOSED_OPTION) return null;
        return reponse == 0 ? 1 : 2;
    }

    private void appliqueResultatStub(int[][] resultat, String libelle) {
        if (resultat == null) {
            System.out.println("La fonction " + libelle + " n'a pas retourne d'image.");
            return;
        }
        appliqueFiltreGlobal(resultat);
    }

    private void activeMenusNG()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(true);
        jMenuHistogramme.setEnabled(true);
        jMenuContours.setEnabled(true);
        jMenuSeuillage.setEnabled(true);
        jMenuFiltrageLineaire.setEnabled(true);
        jMenuTraitementNonLineaire.setEnabled(true);
    }
    
    private void activeMenusRGB()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
        jMenuContours.setEnabled(false);
        jMenuSeuillage.setEnabled(false);
        jMenuFiltrageLineaire.setEnabled(false);
        jMenuTraitementNonLineaire.setEnabled(false);
    }

    private void jMenuItemFiltrePasseBasIdealActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Filtrage linéaire > Global > Passe-bas idéal");
        Integer frequenceCoupure = demandeEntier("Fréquence de coupure", 1);
        if (frequenceCoupure == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(FiltrageLineaireGlobal.filtrePasseBasIdeal(matrice, frequenceCoupure));
    }

    private void jMenuItemFiltrePasseHautIdealActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Filtrage linéaire > Global > Passe-haut idéal");
        Integer frequenceCoupure = demandeEntier("Fréquence de coupure", 1);
        if (frequenceCoupure == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(FiltrageLineaireGlobal.filtrePasseHautIdeal(matrice, frequenceCoupure));
    }

    private void jMenuItemFiltrePasseBasButterworthActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Filtrage lineaire > Global > Passe-bas Butterworth");
        Integer frequenceCoupure = demandeEntier("Frequence de coupure", 1);
        if (frequenceCoupure == null) return;
        Integer ordre = demandeEntier("Ordre du filtre", 1);
        if (ordre == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(FiltrageLineaireGlobal.filtrePasseBasButterworth(matrice, frequenceCoupure, ordre));
    }

    private void jMenuItemFiltrePasseHautButterworthActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Filtrage lineaire > Global > Passe-haut Butterworth");
        Integer frequenceCoupure = demandeEntier("Fréquence de coupure", 1);
        if (frequenceCoupure == null) return;
        Integer ordre = demandeEntier("Ordre du filtre", 1);
        if (ordre == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(FiltrageLineaireGlobal.filtrePasseHautButterworth(matrice, frequenceCoupure, ordre));
    }

    private Double demandeDouble(String libelle, double minimum) {
        while (true) {
            String valeur = JOptionPane.showInputDialog(this, libelle + " :", minimum);
            if (valeur == null) return null;

            try {
                double nombre = Double.parseDouble(valeur.trim());
                if (nombre >= minimum) return nombre;
            }
            catch (NumberFormatException ignored) {
            }

            JOptionPane.showMessageDialog(this, libelle + " doit etre un nombre superieur ou egal a " + minimum + ".", "Valeur invalide", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Integer demandeEntier(String libelle, int minimum) {
        while (true) {
            String valeur = JOptionPane.showInputDialog(this, libelle + " :", minimum);
            if (valeur == null) return null;

            try {
                int entier = Integer.parseInt(valeur.trim());
                if (entier >= minimum) return entier;
            }
            catch (NumberFormatException ignored) {
            }

            JOptionPane.showMessageDialog(this, libelle + " doit être un entier supérieur ou égal à " + minimum + ".", "Valeur invalide", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Integer demandeTailleMasqueImpaire() {
        while (true) {
            Integer tailleMasque = demandeEntier("Taille du masque", 1);
            if (tailleMasque == null) return null;
            if (tailleMasque % 2 == 1) return tailleMasque;

            JOptionPane.showMessageDialog(this, "La taille du masque doit etre impaire.", "Valeur invalide", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void appliqueFiltreGlobal(int[][] matrice) {
        try {
            if (matrice == null) {
                JOptionPane.showMessageDialog(this, "Le filtre n'a pas retourné d'image.", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            imageNG = new CImageNG(matrice);
            observer.setCImage(imageNG);
            imageRGB = null;
            activeMenusNG();
        }
        catch (CImageNGException ex) {
            JOptionPane.showMessageDialog(this, "Erreur CImageNG : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    private int[][] getMatriceImageNG() {
        try {
            return imageNG.getMatrice();
        }
        catch (CImageNGException ex) {
            JOptionPane.showMessageDialog(this, "Erreur CImageNG : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private int[][] demandeMasqueGeodesique() {
        JFileChooser choix = new JFileChooser();
        int retour = choix.showOpenDialog(this);
        if (retour != JFileChooser.APPROVE_OPTION) return null;

        try {
            return new CImageNG(choix.getSelectedFile()).getMatrice();
        }
        catch (IOException | CImageNGException ex) {
            JOptionPane.showMessageDialog(this, "Impossible de charger le masque geodesique : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void jMenuItemMorphoErosionActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Traitement non-lineaire > Elementaire > Erosion");
        Integer tailleMasque = demandeTailleMasqueImpaire();
        if (tailleMasque == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(MorphoElementaire.erosion(matrice, tailleMasque));
    }

    private void jMenuItemMorphoDilatationActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Traitement non-lineaire > Elementaire > Dilatation");
        Integer tailleMasque = demandeTailleMasqueImpaire();
        if (tailleMasque == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(MorphoElementaire.dilatation(matrice, tailleMasque));
    }

    private void jMenuItemMorphoOuvertureActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Traitement non-lineaire > Elementaire > Ouverture");
        Integer tailleMasque = demandeTailleMasqueImpaire();
        if (tailleMasque == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(MorphoElementaire.ouverture(matrice, tailleMasque));
    }

    private void jMenuItemMorphoFermetureActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Traitement non-lineaire > Elementaire > Fermeture");
        Integer tailleMasque = demandeTailleMasqueImpaire();
        if (tailleMasque == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(MorphoElementaire.fermeture(matrice, tailleMasque));
    }

    private void jMenuItemMorphoDilatationGeodesiqueActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Traitement non-lineaire > Complexe > Dilatation geodesique");
        Integer nbIter = demandeEntier("Nombre d'iterations", 1);
        if (nbIter == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        int[][] masqueGeodesique = demandeMasqueGeodesique();
        if (masqueGeodesique == null) return;
        appliqueFiltreGlobal(MorphoComplexe.dilatationGeodesique(matrice, masqueGeodesique, nbIter));
    }

    private void jMenuItemMorphoReconstructionGeodesiqueActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Traitement non-lineaire > Complexe > Reconstruction geodesique");
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        int[][] masqueGeodesique = demandeMasqueGeodesique();
        if (masqueGeodesique == null) return;
        appliqueFiltreGlobal(MorphoComplexe.reconstructionGeodesique(matrice, masqueGeodesique));
    }

    private void jMenuItemMorphoFiltreMedianActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Traitement non-lineaire > Complexe > Filtre median");
        Integer tailleMasque = demandeTailleMasqueImpaire();
        if (tailleMasque == null) return;
        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;
        appliqueFiltreGlobal(MorphoComplexe.filtreMedian(matrice, tailleMasque));
    }

    private void jMenuItemFiltreMasqueConvolutionActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Filtrage linéaire > Local > Masque de convolution");
        JTextArea textArea = new JTextArea("0 -1 0\n-1 5 -1\n0 -1 0", 6, 24);
        int choix = JOptionPane.showConfirmDialog(this, new JScrollPane(textArea), "Masque de convolution", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (choix != JOptionPane.OK_OPTION) return;

        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        try {
            double[][] masque = parseMasqueConvolution(textArea.getText());
            appliqueFiltreGlobal(FiltrageLineaireLocal.filtreMasqueConvolution(matrice, masque));
        }
        catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Masque invalide", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jMenuItemFiltreMoyenneurActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Filtrage linéaire > Local > Moyenneur");
        Integer tailleMasque = demandeEntier("Taille du masque", 1);
        if (tailleMasque == null) return;

        int[][] matrice = getMatriceImageNG();
        if (matrice == null) return;

        try {
            appliqueFiltreGlobal(FiltrageLineaireLocal.filtreMoyenneur(matrice, tailleMasque));
        }
        catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Valeur invalide", JOptionPane.ERROR_MESSAGE);
        }
    }

    private double[][] parseMasqueConvolution(String texte) {
        String texteMasque = texte.trim();
        if (texteMasque.isEmpty()) {
            throw new IllegalArgumentException("Le masque ne peut pas être vide.");
        }

        String[] lignes = texteMasque.split("\\R+");
        double[][] masque = null;
        int nbColonnes = -1;

        for (int i = 0; i < lignes.length; i++) {
            String[] valeurs = lignes[i].trim().split("[,;\\s]+");

            if (nbColonnes == -1) {
                nbColonnes = valeurs.length;
                masque = new double[lignes.length][nbColonnes];
            }
            else if (valeurs.length != nbColonnes) {
                throw new IllegalArgumentException("Toutes les lignes du masque doivent avoir la même taille.");
            }

            for (int j = 0; j < valeurs.length; j++) {
                try {
                    masque[i][j] = Double.parseDouble(valeurs[j]);
                }
                catch (NumberFormatException ex) {
                    throw new IllegalArgumentException("Le masque doit contenir uniquement des nombres.");
                }
            }
        }

        if (masque.length != nbColonnes) {
            throw new IllegalArgumentException("Le masque doit être carré.");
        }

        if (masque.length % 2 == 0) {
            throw new IllegalArgumentException("La taille du masque doit être impaire.");
        }

        return masque;
    }

    private void ajouteTraceMenu(javax.swing.JMenu menu, String libelle) {
        menu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent e) {
                System.out.println(libelle);
            }

            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });
    }
    
    private void jCheckBoxMenuItemDessinerCerclePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerCerclePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(true);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed

    private void jCheckBoxMenuItemDessinerCercleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCercleActionPerformed
        if (!jCheckBoxMenuItemDessinerCercle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(true);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCercleActionPerformed

    private void jMenuItemFourierAfficherPartieImaginaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed
        try 
        {
            int[][] f_int = imageNG.getMatrice();
            double[][] f = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = f_int[i][j];
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double[][] partieImaginaire = fourier.getPartieImaginaire();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieImaginaire,"Fourier : Affichage de la partie imaginaire");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed

    private void jMenuItemFourierAfficherPartieReelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieReelleActionPerformed
        try 
        {
            int[][] f_int = imageNG.getMatrice();
            double[][] f = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = f_int[i][j];
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double[][] partieReelle = fourier.getPartieReelle();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieReelle,"Fourier : Affichage de la partie reelle");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPartieReelleActionPerformed

    private void jMenuItemFourierAfficherPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPhaseActionPerformed
        try 
        {
            int[][] f_int = imageNG.getMatrice();
            double[][] f = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = f_int[i][j];
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double[][] phase = fourier.getPhase();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,phase,"Fourier : Affichage de la phase");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPhaseActionPerformed

    private void jMenuItemFourierAfficherModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherModuleActionPerformed
        try 
        {
            int[][] f_int = imageNG.getMatrice();
            double[][] f = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = f_int[i][j];
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double[][] module = fourier.getModule();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,module,"Fourier : Affichage du module");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherModuleActionPerformed

    private void jCheckBoxMenuItemDessinerPixelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerPixelActionPerformed
        if (!jCheckBoxMenuItemDessinerPixel.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(true);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.CLIC);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerPixelActionPerformed

    private void jMenuItemEnregistrerSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnregistrerSousActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    if (imageRGB != null) imageRGB.enregistreFormatPNG(fichier);
                    if (imageNG != null) imageNG.enregistreFormatPNG(fichier);
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemEnregistrerSousActionPerformed

    private void jMenuItemOuvrirNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirNGActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    imageNG = new CImageNG(fichier);
                    observer.setCImage(imageNG);
                    imageRGB = null;
                    activeMenusNG();
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemOuvrirNGActionPerformed

    private void jMenuItemNouvelleNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleNGActionPerformed
        JDialogNouvelleCImageNG dialog = new JDialogNouvelleCImageNG(this,true);
        dialog.setVisible(true);
        imageNG = dialog.getCImageNG();
        observer.setCImage(imageNG);
        imageRGB = null;
        activeMenusNG();
    }//GEN-LAST:event_jMenuItemNouvelleNGActionPerformed

    private void jMenuItemCouleurPinceauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCouleurPinceauActionPerformed
        if (imageRGB != null)
        {
            Color newC = JColorChooser.showDialog(this,"Couleur du pinceau",couleurPinceauRGB);
            if (newC != null) couleurPinceauRGB = newC;
            observer.setCouleurPinceau(couleurPinceauRGB);
        }
        
        if (imageNG != null)
        {
            JDialogChoixCouleurNG dialog = new JDialogChoixCouleurNG(this,true,couleurPinceauNG);
            dialog.setVisible(true);
            couleurPinceauNG = dialog.getCouleur();
        }
    }//GEN-LAST:event_jMenuItemCouleurPinceauActionPerformed

    private void jCheckBoxMenuItemDessinerRectanglePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerRectanglePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(true);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed

    private void jCheckBoxMenuItemDessinerRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed
        if (!jCheckBoxMenuItemDessinerRectangle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(true);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed

    private void jCheckBoxMenuItemDessinerLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerLigneActionPerformed
        if (!jCheckBoxMenuItemDessinerLigne.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(true);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_LIGNE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerLigneActionPerformed

    private void jMenuItemNouvelleRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleRGBActionPerformed
        JDialogNouvelleCImageRGB dialog = new JDialogNouvelleCImageRGB(this,true);
        dialog.setVisible(true);
        imageRGB = dialog.getCImageRGB();
        observer.setCImage(imageRGB);
        imageNG = null;
        activeMenusRGB();
    }//GEN-LAST:event_jMenuItemNouvelleRGBActionPerformed

    private void jMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitterActionPerformed

    private void jMenuItemOuvrirRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirRGBActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    imageRGB = new CImageRGB(fichier);
                    observer.setCImage(imageRGB);
                    imageNG = null;
                    activeMenusRGB();
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemOuvrirRGBActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new IsilImageProcessing().setVisible(true));
    }

    public void ClicDetected(UnClicEvent e) 
    {
        if (jCheckBoxMenuItemDessinerPixel.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.setPixel(e.getX(),e.getY(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.setPixel(e.getX(),e.getY(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectLigneDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerLigne.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectRectDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectangle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectCercleDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCercle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectCercleFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCerclePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectRectFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectanglePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDessiner;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCercle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCerclePlein;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerLigne;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerPixel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectangle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectanglePlein;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContours;
    private javax.swing.JMenu jMenuContoursLineaire;
    private javax.swing.JMenu jMenuContoursNonLineaire;
    private javax.swing.JMenu jMenuDessiner;
    private javax.swing.JMenu jMenuFourier;
    private javax.swing.JMenu jMenuFourierAfficher;
    private javax.swing.JMenu jMenuFiltrageLineaire;
    private javax.swing.JMenu jMenuFiltrageLineaireGlobal;
    private javax.swing.JMenu jMenuFiltrageLineaireLocal;
    private javax.swing.JMenu jMenuHistogramme;
    private javax.swing.JMenuItem jMenuHistogrammeAfficher;
    private javax.swing.JMenuItem jMenuHistogrammeParametres;
    private javax.swing.JMenu jMenuHistogrammeRehaussement;
    private javax.swing.JMenu jMenuImage;
    private javax.swing.JMenuItem jMenuItemHistogrammeEgalisation;
    private javax.swing.JMenuItem jMenuItemHistogrammeGamma;
    private javax.swing.JMenuItem jMenuItemHistogrammeLineaire;
    private javax.swing.JMenuItem jMenuItemHistogrammeLineaireSaturation;
    private javax.swing.JMenuItem jMenuItemHistogrammeNegatif;
    private javax.swing.JMenuItem jMenuItemMorphoDilatation;
    private javax.swing.JMenuItem jMenuItemMorphoDilatationGeodesique;
    private javax.swing.JMenuItem jMenuItemMorphoErosion;
    private javax.swing.JMenuItem jMenuItemMorphoFermeture;
    private javax.swing.JMenuItem jMenuItemMorphoFiltreMedian;
    private javax.swing.JMenuItem jMenuItemMorphoOuverture;
    private javax.swing.JMenuItem jMenuItemMorphoReconstructionGeodesique;
    private javax.swing.JMenuItem jMenuItemCouleurPinceau;
    private javax.swing.JMenuItem jMenuItemContoursGradientBeucher;
    private javax.swing.JMenuItem jMenuItemContoursGradientDilatation;
    private javax.swing.JMenuItem jMenuItemContoursGradientErosion;
    private javax.swing.JMenuItem jMenuItemContoursGradientPrewitt;
    private javax.swing.JMenuItem jMenuItemContoursGradientSobel;
    private javax.swing.JMenuItem jMenuItemContoursLaplacien4;
    private javax.swing.JMenuItem jMenuItemContoursLaplacien8;
    private javax.swing.JMenuItem jMenuItemContoursLaplacienNonLineaire;
    private javax.swing.JMenuItem jMenuItemEnregistrerSous;
    private javax.swing.JMenuItem jMenuItemFiltrePasseBasButterworth;
    private javax.swing.JMenuItem jMenuItemFiltrePasseBasIdeal;
    private javax.swing.JMenuItem jMenuItemFiltrePasseHautButterworth;
    private javax.swing.JMenuItem jMenuItemFiltrePasseHautIdeal;
    private javax.swing.JMenuItem jMenuItemFiltreMasqueConvolution;
    private javax.swing.JMenuItem jMenuItemFiltreMoyenneur;
    private javax.swing.JMenuItem jMenuItemFourierAfficherModule;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieImaginaire;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieReelle;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPhase;
    private javax.swing.JMenuItem jMenuItemNouvelleNG;
    private javax.swing.JMenuItem jMenuItemNouvelleRGB;
    private javax.swing.JMenuItem jMenuItemOuvrirNG;
    private javax.swing.JMenuItem jMenuItemOuvrirRGB;
    private javax.swing.JMenu jMenuMorphoComplexe;
    private javax.swing.JMenu jMenuMorphoElementaire;
    private javax.swing.JMenu jMenuNouvelle;
    private javax.swing.JMenu jMenuOuvrir;
    private javax.swing.JMenuItem jMenuQuitter;
    private javax.swing.JMenu jMenuSeuillage;
    private javax.swing.JMenuItem jMenuItemSeuillageAutomatique;
    private javax.swing.JMenuItem jMenuItemSeuillageDouble;
    private javax.swing.JMenuItem jMenuItemSeuillageSimple;
    private javax.swing.JMenu jMenuTraitementNonLineaire;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
}
